# .readthedocs.yaml configuration file

# Required: specify the version of the configuration file
version: 2

sphinx:
  builder: html
  configuration: conf.py
  fail_on_warning: true

# Build configuration
build:
  # Set the operating system for the build environment
  os: ubuntu-22.04

  # Specify tools and their versions needed for the build
  tools:
    python: "3.12"

# Python environment configuration
python:
  install:
    - requirements: docs/requirements.txt  # Path to your requirements.txt file

# Sphinx configuration
sphinx:
  configuration: docs/source/conf.py  # Path to your Sphinx configuration file

# Dependencies installation
dependencies:
  # Install Sphinx and Sphinx RTD theme using pip
  pip:
    - sphinx
    - sphinx-rtd-theme

# Build process customization
# Specify the output formats for the documentation build
formats:
  - htmlzip
  - pdf
  - epub

# Additional notes
# Customize further based on your project's specific requirements and structure



